# Generated by Django 5.0.6 on 2024-10-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=550, verbose_name='Имя пользователя'),
        ),
    ]
