# Generated by Django 5.0.6 on 2024-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0004_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='moderarated',
            field=models.BooleanField(default=False),
        ),
    ]
