# Generated by Django 5.0.6 on 2024-10-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0007_customuser_groups_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
