# Generated by Django 5.0.6 on 2024-10-09 14:18

import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0011_alter_city_options_alter_city_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='moderarated',
            field=models.BooleanField(default=django.contrib.gis.geos.point.Point(50, 30)),
        ),
    ]
