# Generated by Django 5.0.6 on 2024-10-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0012_alter_city_moderarated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='RusCity',
        ),
    ]
