# Generated by Django 5.0.6 on 2024-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('russiancities', '0013_rename_city_ruscity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruscity',
            name='moderarated',
            field=models.BooleanField(default=False),
        ),
    ]
